### ISSUE TITLE
Fix Exception related to ScreenUtilInit state

### ISSUE THREAD

**Issue by AnisimovTema** [TemityStolyarov/assistent_app#12]
Ошибка заключается в использовании параметра limit, хранящегося в SharedPreferences, параметр не успевал подгружаться, и в макет передавалось null-значение, при замене ненулевого оператора ! на ?? с дефолтным значением, интерфейс начал скакать

**Comment by TemityStolyarov** [comment]
Ошибка решена в ходе добавления управления состояниями BLoC

**Comment by AnisimovTema** [comment]
Ошибка решена в ходе добавления управления состояниями BLoC, PR #4
